eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
words: boat,book,vote,seat,backpack,partition,groundhog
server:
  port: ${PORT:${SERVER_PORT:0}}
#added below to enable all endpoints of actuator. Should be done only on test server.
management:
  endpoints:
    web:
      exposure:
        include: "*"
#---
#words: fallback
#eureka.client.serviceUrl.defaultZone= http://localhost:8010/eureka/
#words= boat,book,vote,seat,backpack,partition,groundhog
#server.port=${PORT:${SERVER_PORT:0}}
#---
#spring:
#  profiles: cold-noun
#words: icicle,refrigerator,blizzard,snowball